-- MySQL Script generated by MySQL Workbench
-- Fri Jan  3 21:34:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema it_happens
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema it_happens
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `it_happens` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `it_happens` ;

-- -----------------------------------------------------
-- Table `it_happens`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `it_happens`.`area` ;

CREATE TABLE IF NOT EXISTS `it_happens`.`area` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `continent` TEXT NOT NULL,
  `country` TEXT NOT NULL,
  `city` TEXT NOT NULL,
  `zip_code` INT(11) NOT NULL,
  `address` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 75
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `it_happens`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `it_happens`.`categories` ;

CREATE TABLE IF NOT EXISTS `it_happens`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `categories` VARCHAR(50) NOT NULL,
  `parent` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `it_happens`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `it_happens`.`event` ;

CREATE TABLE IF NOT EXISTS `it_happens`.`event` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `ownerID` INT(11) NOT NULL,
  `venueID` INT(11) NOT NULL,
  `categoryID` INT(11) NOT NULL,
  `startingDate` DATETIME NOT NULL,
  `endingDate` DATETIME NULL DEFAULT NULL,
  `description` TEXT NOT NULL,
  `tags` TEXT NULL DEFAULT NULL,
  `ticketprice` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `it_happens`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `it_happens`.`users` ;

CREATE TABLE IF NOT EXISTS `it_happens`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `areaID` INT(11) NOT NULL,
  `Username` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `name` TEXT NOT NULL,
  `surname` TEXT NOT NULL,
  `age` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `area_id` (`areaID` ASC) VISIBLE,
  CONSTRAINT `area_id`
    FOREIGN KEY (`areaID`)
    REFERENCES `it_happens`.`area` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `it_happens`.`event_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `it_happens`.`event_list` ;

CREATE TABLE IF NOT EXISTS `it_happens`.`event_list` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` TEXT NOT NULL,
  `creatorID` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `creator_id` (`creatorID` ASC) VISIBLE,
  CONSTRAINT `creator_id`
    FOREIGN KEY (`creatorID`)
    REFERENCES `it_happens`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `it_happens`.`num`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `it_happens`.`num` ;

CREATE TABLE IF NOT EXISTS `it_happens`.`num` (
  `id` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `it_happens`.`venues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `it_happens`.`venues` ;

CREATE TABLE IF NOT EXISTS `it_happens`.`venues` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `accID` INT(11) NOT NULL,
  `areaID` INT(11) NOT NULL,
  `name` TEXT NOT NULL,
  `capacity` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 93
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
